name: go_services_echo_deploy

on:
  push:
    branches: [ main ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          echo ${{ github.event.ref }}
          echo before ${{ github.event.before }}
          echo after ${{ github.event.after }}
          echo $REF
          echo $BEFORE
          echo $AFTER
    env:
      REF: ${{ github.event.ref }}
      BEFORE: ${{ github.event.before }}
      AFTER: ${{ github.event.after }}
