name: go_services_echo_deploy

on:
  push:
    branches: [ main ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          echo ${{ github.event.push.ref }}
          echo before ${{ github.event.push.before }}
          echo after ${{ github.event.push.after }}
