name: go_services_echo_deploy

on:
  push:
    branches: [ main ]

jobs:
  echo:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          echo before ${{ github.event.push.before }}
          echo after ${{ github.event.push.after }}
