name: reusable_tagging

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ inputs.tag }} > TAG_NAME
          git tag $(cat TAG_NAME)
          echo hoge
          git push origin $(cat TAG_NAME)
